#!/bin/bash
echo "Hello, World! - System Info"
echo "==============================="
echo "Date: $(date)"
echo "User: $(whoami)"
echo ""
echo "🔍 CURRENT WORKING DIRECTORY VERIFICATION:"
echo "Directory: $(pwd)"
echo "Full path: $(realpath .)"
echo ""
echo "📁 FILES IN CURRENT DIRECTORY:"
ls -la
echo ""
echo "📊 DIRECTORY INFO:"
echo "Total files: $(ls -1 | wc -l)"
echo "Hidden files: $(ls -1a | grep '^\.' | wc -l)"
echo ""
echo "💻 SYSTEM INFO:"
echo "OS: $(uname -s)"
echo "Shell: $SHELL"
echo "Uptime: $(uptime | cut -d',' -f1)"
