{ config, pkgs, lib, ... }:

{
  # NixOS system configuration example
  # This is a placeholder for when you want to add NixOS support

  # imports = [
  #   ./hardware-configuration.nix  # Generated by nixos-generate-config
  # ];

  # Boot loader
  # boot.loader.systemd-boot.enable = true;
  # boot.loader.efi.canTouchEfiVariables = true;

  # Networking
  # networking.hostName = "nixos-laptop";
  # networking.networkmanager.enable = true;

  # Time zone
  # time.timeZone = "America/New_York";

  # Users
  # users.users.kurro = {
  #   isNormalUser = true;
  #   extraGroups = [ "wheel" "networkmanager" ];
  #   shell = pkgs.zsh;
  # };

  # Enable unfree packages
  # nixpkgs.config.allowUnfree = true;

  # System packages
  # environment.systemPackages = with pkgs; [
  #   vim
  #   git
  # ];

  # Enable programs
  # programs.zsh.enable = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # system.stateVersion = "24.11";
}
